# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'شاخه',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=30, verbose_name='نام')),
                ('comment_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('date_send',
                 models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 16, 23, 29, 6, 352691),
                                      verbose_name='زمان ارسال')),
                ('comment', models.TextField(verbose_name='محتوای کامنت')),
            ],
            options={
                'verbose_name': 'کامنت',
                'ordering': ['comment_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='محتوای پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_title', models.CharField(max_length=100, verbose_name='عنوان افتخارات')),
                ('fest_logo', models.FileField(upload_to='Festivallogo/%Y/%m/%d', verbose_name='لوگوی افتخارات')),
                ('fest_text', models.TextField(verbose_name='توضیح افتخارات')),
                ('fest_url', models.URLField(verbose_name='آدرس افتخارات')),
            ],
            options={
                'verbose_name': 'عنوان و افتخار',
                'ordering': ['fest_title'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=50, verbose_name='زیرشاخه')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebCastle.Category',
                                               verbose_name='شاخه')),
            ],
            options={
                'verbose_name': 'زیرشاخه',
                'ordering': ['subcategory'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='ایمیل مشترکین')),
            ],
            options={
                'verbose_name': 'خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('vision', models.TextField(verbose_name='چشم انداز')),
                ('mission', models.TextField(verbose_name='ماموریت')),
                ('service_product', models.TextField(verbose_name='محصولات و خدمات')),
                ('Webpage_logo', models.FileField(upload_to='Webpagelogo/%Y/%m/%d', verbose_name='وب لوگو')),
                ('Webpage_url', models.URLField(verbose_name='آدرس سایت')),
                ('Sub', models.ManyToManyField(to='WebCastle.SubCategory', verbose_name='دسته مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صفحه وب سایت',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='subscribe',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebCastle.Webpage',
                                    verbose_name='اشتراک وب'),
        ),
        migrations.AddField(
            model_name='festival',
            name='webpage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='WebCastle.Webpage',
                                    verbose_name='افتخارات وب سایت'),
        ),
    ]
