# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:10
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebCastle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('national_code', models.CharField(max_length=10)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='محتوای کامنت'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 17, 14, 40, 33, 15254),
                                       verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='محتوای پیام'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fest_text',
            field=ckeditor.fields.RichTextField(verbose_name='توضیح افتخارات'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='mission',
            field=ckeditor.fields.RichTextField(verbose_name='ماموریت'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='service_product',
            field=ckeditor.fields.RichTextField(verbose_name='محصولات و خدمات'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='vision',
            field=ckeditor.fields.RichTextField(verbose_name='چشم انداز'),
        ),
    ]
