# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebCastle', '0002_auto_20160617_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 17, 14, 41, 35, 927298),
                                       verbose_name='زمان ارسال'),
        ),
    ]
