# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebCastle', '0003_auto_20160617_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='محتوای کامنت'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 17, 20, 6, 28, 16380),
                                       verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='محتوای پیام'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fest_text',
            field=models.TextField(verbose_name='توضیح افتخارات'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='mission',
            field=models.TextField(verbose_name='ماموریت'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='service_product',
            field=models.TextField(verbose_name='محصولات و خدمات'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='vision',
            field=models.TextField(verbose_name='چشم انداز'),
        ),
    ]
