# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebCastle', '0005_auto_20160618_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 18, 20, 17, 6, 878277),
                                       verbose_name='زمان ارسال'),
        ),
    ]
